# This is a basic workflow to help you get started with Actions

name: Container

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 
  pull-request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.15

    steps:
      - name: Log node version
        run: | 
           node -v
           cat /etc/os-release
  docker-steps:
    runs-on: ubuntu-latest
    container: 
      image: node:10.18.0-jessie
    steps:
    - name: log node version
      run: node -v
    - name: Step with docker
      uses: docker://node:12.14.1-alpine3.10
      with: 
        entrypoint: /usr/local/bin/node
        args:  -v  