name: Contexts
on: 
  push: 
    branches: ["main"]
  pull_request:
    type: [opened,reopened]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains('hello','ll')}}
          echo ${{ startsWith('hello','he')}}
          echo ${{ endsWith('hello','lo')}}
          echo ${{ format('hello {0} {1} {2}','word','!','o')}}
  one:
    runs-on: ubuntu-latest 
    if: github.event_name=='push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        id: github_context_step
        run: eccho "$GITHUB_CONTEXT"
        
      - name: Dump job context
        if: failure()
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        if: always()
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'