# This is a basic workflow to help you get started with Actions

name: Container-services

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app: 
        image: danikr238/web-bookings1.0 
        ports: 
          - 8080:8080
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Get url
        run : curl https://localhost:8080
      

   